### ISSUE TITLE
Regarding Geoext 2

### ISSUE THREAD

**Issue by mahi14** [geoext/geoext2#382]
Actually i am using Geoext for web mapping in web GIS and I am using tree.js example for overlay and create tree in one panel. But the problem is that the layer that i am using is not zooming in and out at max extent. here is that example for my own layer
![overlay](https://cloud.githubusercontent.com/assets/17475033/13321365/9dff98ee-dbf4-11e5-8619-1ba84d5838fb.png)

**Comment by bentrm** [comment]
@mahi14, please point questions about the usage of the library to the GeoExt [mailing list](http://www.geoext.org/cgi-bin/mailman/listinfo/users) or [Stack Overflow](http://stackoverflow.com/search?q=geoext). GitHub Issues are used for bug tracking only. 

Either way, additional information about your specific problem will be required to help you. You'll need to attach some reproducible code and a description of what you're trying to achieve. 

If you think your problem is due to a bug in GeoExt, feel free to reopen or post a new issue. Thanks.
